name: admin_panal_start
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.0.10+1
  fl_chart: ^1.1.1
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.4
  cached_network_image: ^3.3.0
  gap: ^3.0.1
  get: ^4.6.6
  provider: ^6.1.2
  intl: ^0.20.2
  url_launcher: ^6.2.2
  get_storage: ^2.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/